### ISSUE TITLE
Mongodb aggregate fails

### ISSUE THREAD

**Issue by yetithefoot** [RisingStack/trace-nodejs#111]
Hey,

Im using `mongojs` with mongodb 3.2.7. When I perform `.aggregate` mongodb returns an error:
```
TypeError: Cannot read property 'out' of undefined
    at Collection.aggregate (./searcher/node_modules/mongodb/lib/collection.js:2488:20)
    at wrapQuery (./searcher/node_modules/@risingstack/trace/lib/instrumentations/utils/wrapQuery.js:73:21)
    at .aggregate (./searcher/node_modules/@risingstack/trace/lib/instrumentations/mongodb.js:46:30)
    at ./searcher/node_modules/mongojs/lib/collection.js:272:27
    at ./searcher/node_modules/mongojs/lib/collection.js:20:7
    at apply (./searcher/node_modules/thunky/index.js:16:28)
    at ._getConnection (./searcher/node_modules/thunky/index.js:27:3)
    at _getCollection (./searcher/node_modules/mongojs/lib/collection.js:17:10)
    at ./searcher/node_modules/mongojs/lib/collection.js:269:10
    at ./searcher/node_modules/mongojs/lib/cursor.js:12:5
```

This is my `npm ls --depth=0`
```
./searcher
├── @risingstack/trace@2.15.2
├── colors@1.1.2
├── config@1.21.0
├── elasticsearch@11.0.1
├── escape-string-regexp@1.0.5
├── joi@8.4.2
├── moment@2.13.0
├── mongojs@2.4.0
├── nodemon@1.9.2
├── q@1.4.1
└── restify@4.1.0
```

What is the strategy for those scenarios? Maybe I can exclude some instrumentations via config.
Now I have to disable tracing. 😢

**Comment by gergelyke** [comment]
we are still investigating the mongo aggregation issue - in the meantime we have released 2.16.0. Here you can use the `TRACE_DISABLE_INSTRUMENTATIONS` env var like `TRACE_DISABLE_INSTRUMENTATIONS=mongodb` to disable the mongo instrumentation. Also, if you are using a `trace.config.js` you can add `disableInstrumentations` property - an array containing module names: https://github.com/RisingStack/trace-nodejs/blob/master/README.md

**Comment by yetithefoot** [comment]
@gergelyke looks like everything is OK in `2.16.1`

**Comment by gergelyke** [comment]
thanks!

**Comment by jpadilla** [comment]
Ran into something similar

```
ERROR! TypeError: Cannot read property 'then' of undefined
    at db.then (/Users/jpadilla/Projects/Alias/gm/backend/app/tasks/adapters/mongodb.js:45:11)
    at propagateAslWrapper (/Users/jpadilla/Projects/Alias/gm/backend/node_modules/async-listener/index.js:421:23)
    at /Users/jpadilla/Projects/Alias/gm/backend/node_modules/async-listener/glue.js:188:31
    at /Users/jpadilla/Projects/Alias/gm/backend/node_modules/async-listener/index.js:458:70
```

In `mongodb.js:45:11` I have something like this:

```
collection.findOneAndUpdate(query, update, opts).then((r) => {...})
```

Adding `findOneAndUpdate` to https://github.com/RisingStack/trace-nodejs/blob/master/lib/instrumentations/mongodb.js#L51 "fixed it"
