### ISSUE TITLE
NPM install keeps failing with -- Invalid name: "@risingstack/trace"

### ISSUE THREAD

**Issue by icecubed** [RisingStack/trace-nodejs#112]
I am trying to test out trace and using npm to install the package seems to fail with the following. 

```
# npm install @risingstack/trace --save
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@risingstack/trace" "--save"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! Invalid name: "@risingstack/trace"
```

My npm version is 3.8.6  The full debug log for npm is as follows 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@risingstack/trace',
1 verbose cli   '--save' ]
2 info using npm@3.8.6
3 info using node@v6.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @risingstack/trace
8 silly fetchNamedPackageData @risingstack/trace
9 silly mapToRegistry name @risingstack/trace
10 silly mapToRegistry scope (from package name) @risingstack
11 verbose mapToRegistry no registry URL found in name for scope @risingstack
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@risingstack/trace',
14 silly mapToRegistry   scope: '@risingstack',
14 silly mapToRegistry   name: '@risingstack/trace',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@risingstack%2ftrace
16 verbose request uri https://registry.npmjs.org/@risingstack%2ftrace
17 verbose request no auth needed
18 info attempt registry request try #1 at 6:42:56 AM
19 verbose request id 103a38e296e9cee7
20 verbose etag "39QVRCM4H7X7R2248SFZIZRGO"
21 http request GET https://registry.npmjs.org/@risingstack%2ftrace
22 http 304 https://registry.npmjs.org/@risingstack%2ftrace
23 verbose headers { date: 'Fri, 15 Jul 2016 06:42:56 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   etag: '"39QVRCM4H7X7R2248SFZIZRGO"',
23 verbose headers   age: '0',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-dfw1848-DFW',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1468564976.347880,VS0,VE550',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 304,
24 silly get   { date: 'Fri, 15 Jul 2016 06:42:56 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=0',
24 silly get     etag: '"39QVRCM4H7X7R2248SFZIZRGO"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-dfw1848-DFW',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1468564976.347880,VS0,VE550',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose etag https://registry.npmjs.org/@risingstack%2ftrace from cache
26 verbose get saving @risingstack/trace to /root/.npm/registry.npmjs.org/_40risingstack_252ftrace/.cache.json
27 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
28 silly install normalizeTree
29 silly loadCurrentTree Finishing
30 silly loadIdealTree Starting
31 silly install loadIdealTree
32 silly cloneCurrentTree Starting
33 silly install cloneCurrentTreeToIdealTree
34 silly cloneCurrentTree Finishing
35 silly loadShrinkwrap Starting
36 silly install loadShrinkwrap
37 silly loadShrinkwrap Finishing
38 silly loadAllDepsIntoIdealTree Starting
39 silly install loadAllDepsIntoIdealTree
40 silly resolveWithNewModule @risingstack/trace@2.18.4 checking installable status
41 silly cache add args [ '@risingstack/trace', null ]
42 verbose cache add spec @risingstack/trace
43 silly cache add parsed spec Result {
43 silly cache add   raw: '@risingstack/trace',
43 silly cache add   scope: '@risingstack',
43 silly cache add   name: '@risingstack/trace',
43 silly cache add   rawSpec: '',
43 silly cache add   spec: 'latest',
43 silly cache add   type: 'tag' }
44 silly addNamed @risingstack/trace@latest
45 verbose addNamed "latest" is being treated as a dist-tag for @risingstack/trace
46 info addNameTag [ '@risingstack/trace', 'latest' ]
47 silly mapToRegistry name @risingstack/trace
48 silly mapToRegistry scope (from package name) @risingstack
49 verbose mapToRegistry no registry URL found in name for scope @risingstack
50 silly mapToRegistry using default registry
51 silly mapToRegistry registry https://registry.npmjs.org/
52 silly mapToRegistry data Result {
52 silly mapToRegistry   raw: '@risingstack/trace',
52 silly mapToRegistry   scope: '@risingstack',
52 silly mapToRegistry   name: '@risingstack/trace',
52 silly mapToRegistry   rawSpec: '',
52 silly mapToRegistry   spec: 'latest',
52 silly mapToRegistry   type: 'tag' }
53 silly mapToRegistry uri https://registry.npmjs.org/@risingstack%2ftrace
54 verbose addNameTag registry:https://registry.npmjs.org/@risingstack%2ftrace not in flight; fetching
55 verbose get https://registry.npmjs.org/@risingstack%2ftrace not expired, no request
56 silly addNameTag next cb for @risingstack/trace with tag latest
57 silly addNamed @risingstack/trace@2.18.4
58 verbose addNamed "2.18.4" is a plain semver version for @risingstack/trace
59 silly rollbackFailedOptional Starting
60 silly rollbackFailedOptional Finishing
61 silly runTopLevelLifecycles Starting
62 silly runTopLevelLifecycles Finishing
63 silly install printInstalled
64 verbose stack Error: Invalid name: "@risingstack/trace"
64 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
64 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
64 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
64 verbose stack     at Array.forEach (native)
64 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
64 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
64 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
64 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:203:31
64 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
64 verbose stack     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/glob/glob.js:146:7)
65 verbose cwd /srv/www/v2
66 error Linux 3.16.0-4-amd64
67 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@risingstack/trace" "--save"
68 error node v6.0.0
69 error npm  v3.8.6
70 error Invalid name: "@risingstack/trace"
71 error If you need help, you may report this error at:
71 error     <https://github.com/npm/npm/issues>
72 verbose exit [ 1, true ]
```

**Comment by gergelyke** [comment]
Hello @icecubed,

that's strange, it should only happen if your npm does not support private modules, which clearly cannot be the case. Could you try with npm@2 latest?
