### ISSUE TITLE
Invalid name: "@risingstack/trace"

### ISSUE THREAD

**Issue by marcelkobainGIT** [RisingStack/trace-nodejs#134]
Hello,

I'm not able to install "trace"
I have the message : "Invalid name: "@risingstack/trace"

here the stack : 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@risingstack/trace',
1 verbose cli   '--save' ]
2 info using npm@2.15.11
3 info using node@v4.7.3
4 verbose install initial load of /mnt/hgfs/GIT/web-cdb-console/package.json
5 verbose readDependencies loading dependencies from /mnt/hgfs/GIT/web-cdb-console/package.json
6 silly cache add args [ '@risingstack/trace', null ]
7 verbose cache add spec @risingstack/trace
8 silly cache add parsed spec Result {
8 silly cache add   raw: '@risingstack/trace',
8 silly cache add   scope: '@risingstack',
8 silly cache add   name: '@risingstack/trace',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed @risingstack/trace@latest
10 verbose addNamed "latest" is being treated as a dist-tag for @risingstack/trace
11 info addNameTag [ '@risingstack/trace', 'latest' ]
12 silly mapToRegistry name @risingstack/trace
13 silly mapToRegistry scope (from package name) @risingstack
14 verbose mapToRegistry no registry URL found in name for scope @risingstack
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry data Result {
17 silly mapToRegistry   raw: '@risingstack/trace',
17 silly mapToRegistry   scope: '@risingstack',
17 silly mapToRegistry   name: '@risingstack/trace',
17 silly mapToRegistry   rawSpec: '',
17 silly mapToRegistry   spec: 'latest',
17 silly mapToRegistry   type: 'tag' }
18 silly mapToRegistry uri https://registry.npmjs.org/@risingstack%2ftrace
19 verbose addNameTag registry:https://registry.npmjs.org/@risingstack%2ftrace not in flight; fetching
20 verbose request uri https://registry.npmjs.org/@risingstack%2ftrace
21 verbose request no auth needed
22 info attempt registry request try #1 at 11:47:34 AM
23 verbose request id b55863fe9fd7dc8a
24 verbose etag W/"58f279e6-90f92"
25 verbose lastModified Sat, 15 Apr 2017 19:52:06 GMT
26 http request GET https://registry.npmjs.org/@risingstack%2ftrace
27 http 304 https://registry.npmjs.org/@risingstack%2ftrace
28 verbose headers { server: 'nginx/1.10.1',
28 verbose headers   'last-modified': 'Sat, 15 Apr 2017 19:52:06 GMT',
28 verbose headers   etag: '"58f279e6-90f92"',
28 verbose headers   'cache-control': 'max-age=0',
28 verbose headers   'accept-ranges': 'bytes',
28 verbose headers   date: 'Wed, 19 Apr 2017 09:47:35 GMT',
28 verbose headers   via: '1.1 varnish',
28 verbose headers   connection: 'keep-alive',
28 verbose headers   'x-served-by': 'cache-cdg8730-CDG',
28 verbose headers   'x-cache': 'MISS',
28 verbose headers   'x-cache-hits': '0',
28 verbose headers   'x-timer': 'S1492595255.047038,VS0,VE735' }
29 silly get cb [ 304,
29 silly get   { server: 'nginx/1.10.1',
29 silly get     'last-modified': 'Sat, 15 Apr 2017 19:52:06 GMT',
29 silly get     etag: '"58f279e6-90f92"',
29 silly get     'cache-control': 'max-age=0',
29 silly get     'accept-ranges': 'bytes',
29 silly get     date: 'Wed, 19 Apr 2017 09:47:35 GMT',
29 silly get     via: '1.1 varnish',
29 silly get     connection: 'keep-alive',
29 silly get     'x-served-by': 'cache-cdg8730-CDG',
29 silly get     'x-cache': 'MISS',
29 silly get     'x-cache-hits': '0',
29 silly get     'x-timer': 'S1492595255.047038,VS0,VE735' } ]
30 verbose etag https://registry.npmjs.org/@risingstack%2ftrace from cache
31 verbose get saving @risingstack/trace to /home/cap/.npm/registry.npmjs.org/_40risingstack_252ftrace/.cache.json
32 verbose correctMkdir /home/cap/.npm correctMkdir not in flight; initializing
33 silly addNameTag next cb for @risingstack/trace with tag latest
34 silly addNamed @risingstack/trace@3.6.2
35 verbose addNamed "3.6.2" is a plain semver version for @risingstack/trace
36 verbose stack Error: Invalid name: "@risingstack/trace"
36 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
36 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
36 verbose stack     at Array.forEach (native)
36 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
36 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
36 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
36 verbose stack     at serverjs_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:177:29)
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:172:5
36 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
37 verbose cwd /mnt/hgfs/GIT/web-cdb-console
38 error Linux 3.13.0-24-generic
39 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@risingstack/trace" "--save"
40 error node v4.7.3
41 error npm  v2.15.11
42 error Invalid name: "@risingstack/trace"
43 error If you need help, you may report this error at:
43 error     <https://github.com/npm/npm/issues>
44 verbose exit [ 1, true ]

**Comment by marcelkobainGIT** [comment]
I havec upgrade my npm to 2.15.2 and it is ok.
npm install -g npm@latest-2
