### ISSUE TITLE
spawn ENOTDIR

### ISSUE THREAD

**Issue by hiteshbal91** [RisingStack/trace-nodejs#141]
Hi,

I am facing issue of "spawn ENOTDIR" when I install @risingstack/trace package, and start using it with my node expressjs based application.

Can any body help?

More information: 

I am using pm2 for node application.
risingstack/trace version: 3.11.0

**Comment by gergelyke** [comment]
Additional stack trace:

```
Error: spawn ENOTDIR

at exports._errnoException (util.js:870:11)

at ChildProcess.spawn (internal/child_process.js:298:11)

at ChildProcess.spawn (/opt/node/lib/node_modules/pm2/node_modules/pmx/node_modules/vxx/node_modules/continuation-local-storage/node_modules/async-listener/index.js:120:29)

at exports.spawn (child_process.js:362:9)

at Object.exports.execFile (child_process.js:151:15)

at Security.collectDependencies (/opt/built-flow/built-api-express/node_modules/@risingstack/trace/lib/agent/security/security.js:118:16)

at Security.sendDependencies (/opt/built-flow/built-api-express/node_modules/@risingstack/trace/lib/agent/security/security.js:144:8)

at Security.initialize (/opt/built-flow/built-api-express/node_modules/@risingstack/trace/lib/agent/security/security.js:22:8)

at /opt/built-flow/built-api-express/node_modules/@risingstack/trace/lib/agent/index.js:108:13

at Array.forEach (native)

at /opt/built-flow/built-api-express/node_modules/@risingstack/trace/lib/agent/index.js:107:17

at BufferList._callback (/opt/built-flow/built-api-express/node_modules/@risingstack/trace/lib/agent/api/index.js:322:7)

at BufferList.end (/opt/built-flow/built-api-express/node_modules/@risingstack/trace/node_modules/bl/bl.js:104:10)

at IncomingMessage.onend (_stream_readable.js:498:10)

at IncomingMessage.g (events.js:260:16)

at emitNone (events.js:72:20)

at IncomingMessage.emit (events.js:166:7)

at endReadableNT (_stream_readable.js:913:12)

at /opt/node/lib/node_modules/pm2/node_modules/pmx/node_modules/vxx/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31

at nextTickCallbackWith2Args (node.js:442:9)

at process._tickDomainCallback [as _tickCallback] (node.js:397:17)
```

**Comment by szdavid92** [comment]
This seems to be thrown in the security agent. @tothandras could you take a look?

**Comment by tothandras** [comment]
sure @szdavid92, already on it!

**Comment by szdavid92** [comment]
Hmm, seems something is funky with your environment. Could you try running this for me:

```
var execFileSync = require('child-process')
execFileSync('npm', ['ls', '--json', '--production']).toString()
```

**Comment by tothandras** [comment]
If you encounter similar problems, try to run:
`npm ls --json --production`
and
`console.log(process.cwd())`
in the same environment.
